FROM node:20-alpine
RUN apk add --no-cache libc6-compat openssl
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
COPY prisma ./prisma
RUN npx prisma generate
COPY next.config.mjs tsconfig.json tailwind.config.ts postcss.config.js components.json ./
EXPOSE 3000
CMD ["sh", "-c", "npx prisma migrate deploy && npm run dev"]
